/*
 * Este codigo fue creado por @DuvanBotello
 *  <"Sin lógica no hay paraíso">
 */
package GUI;

import Abstracciones.Abs_deudores;
import Abstracciones.Abs_devoluciones;
import Abstracciones.Abs_material;
import Abstracciones.Abs_prestamo;
import Abstracciones.Abs_usuario;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author DuvanBotello
 * <http://yoaprendo-informatica.blogspot.com.co/ - duvanbotello1008@gmail.com>
 */
public class FReportes extends javax.swing.JFrame {

    private final String link_reportes = "/Reportes/logon.jpg";

    /**
     * Creates new form FReportes
     */
    public FReportes() {
        initComponents();

        desactivar_paneles();
    }

    private void desactivar_paneles() {
        jLabel13.setVisible(false);
        nombre_editorial.setVisible(false);
        p2.setVisible(false);
        btm_generar.setVisible(false);
        btm_generar__devoluciones.setVisible(false);
        consultar_por_documento_mas_fechas.setVisible(false);
        this.setLocationRelativeTo(null);
        cmbtipo_material.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Panel_listados = new javax.swing.JPanel();
        btm_listado_alumnos = new javax.swing.JButton();
        btm_listado_usuarios = new javax.swing.JButton();
        btm_listado_devoluciones = new javax.swing.JButton();
        btm_listado_prestamos = new javax.swing.JButton();
        btm_listado_materiales = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        panles_resporteMateriales = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cmbtipodereporte = new javax.swing.JComboBox<>();
        p2 = new javax.swing.JPanel();
        tdoc_materiales = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        m_fecha_inicial = new com.toedter.calendar.JDateChooser();
        m_fecha_final = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btm_generar = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cmbtipodereporte_devoluciones = new javax.swing.JComboBox<>();
        btm_generar__devoluciones = new javax.swing.JButton();
        consultar_por_documento_mas_fechas = new javax.swing.JPanel();
        doc_devoluciones = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        f_inicial = new com.toedter.calendar.JDateChooser();
        f_final = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btm_generar__deudores = new javax.swing.JButton();
        fecha_actual2 = new com.toedter.calendar.JDateChooser();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel19 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        cmbsegun = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cmbtipo_material = new javax.swing.JComboBox<>();
        btm_generar_material = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        nombre_editorial = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        cmb_usuario_segun = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        btm_generar_usuarios = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VENTANA DE REPORTES - BIBLIOTECA UNI PAMPLONA");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        Panel_listados.setBackground(new java.awt.Color(255, 255, 255));
        Panel_listados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btm_listado_alumnos.setBackground(new java.awt.Color(0, 0, 0));
        btm_listado_alumnos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btm_listado_alumnos.setForeground(new java.awt.Color(255, 255, 255));
        btm_listado_alumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ico_estudiante.png"))); // NOI18N
        btm_listado_alumnos.setText("Generar Listado de Alumnos Por semestre");
        btm_listado_alumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_listado_alumnosActionPerformed(evt);
            }
        });
        Panel_listados.add(btm_listado_alumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 330, 60));

        btm_listado_usuarios.setBackground(new java.awt.Color(0, 0, 0));
        btm_listado_usuarios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btm_listado_usuarios.setForeground(new java.awt.Color(255, 255, 255));
        btm_listado_usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_add_usuario.png"))); // NOI18N
        btm_listado_usuarios.setText("Generar Listado de Usuarios");
        btm_listado_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_listado_usuariosActionPerformed(evt);
            }
        });
        Panel_listados.add(btm_listado_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 280, 60));

        btm_listado_devoluciones.setBackground(new java.awt.Color(0, 0, 0));
        btm_listado_devoluciones.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btm_listado_devoluciones.setForeground(new java.awt.Color(255, 255, 255));
        btm_listado_devoluciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_devolver.png"))); // NOI18N
        btm_listado_devoluciones.setText("Generar Listado de Devoluciones");
        btm_listado_devoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_listado_devolucionesActionPerformed(evt);
            }
        });
        Panel_listados.add(btm_listado_devoluciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 290, 60));

        btm_listado_prestamos.setBackground(new java.awt.Color(0, 0, 0));
        btm_listado_prestamos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btm_listado_prestamos.setForeground(new java.awt.Color(255, 255, 255));
        btm_listado_prestamos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_informacion.png"))); // NOI18N
        btm_listado_prestamos.setText("Generar Listado de Prestamos");
        btm_listado_prestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_listado_prestamosActionPerformed(evt);
            }
        });
        Panel_listados.add(btm_listado_prestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 280, 60));

        btm_listado_materiales.setBackground(new java.awt.Color(0, 0, 0));
        btm_listado_materiales.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btm_listado_materiales.setForeground(new java.awt.Color(255, 255, 255));
        btm_listado_materiales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_llevar.png"))); // NOI18N
        btm_listado_materiales.setText("Generar Listado de Materiales");
        btm_listado_materiales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_listado_materialesActionPerformed(evt);
            }
        });
        Panel_listados.add(btm_listado_materiales, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 300, 60));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        Panel_listados.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -16, 650, 330));

        jTabbedPane1.addTab("Listados", Panel_listados);

        panles_resporteMateriales.setBackground(new java.awt.Color(255, 255, 255));
        panles_resporteMateriales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo de Reporte:");
        panles_resporteMateriales.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        cmbtipodereporte.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmbtipodereporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Consultar Por Documento", "Consultar por Documento + Fechas" }));
        cmbtipodereporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmbtipodereporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtipodereporteActionPerformed(evt);
            }
        });
        panles_resporteMateriales.add(cmbtipodereporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 277, -1));

        p2.setBackground(new java.awt.Color(255, 255, 255));
        p2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Colsultar Por Documento + Fechas:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 14))); // NOI18N
        p2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tdoc_materiales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tdoc_materiales.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tdoc_materialesKeyTyped(evt);
            }
        });
        p2.add(tdoc_materiales, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 26, 180, 30));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("Fecha Inicial:");
        p2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("Ingrese Documento");
        p2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        m_fecha_inicial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p2.add(m_fecha_inicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 150, 20));

        m_fecha_final.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p2.add(m_fecha_final, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 150, -1));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setText("Fecha Final:");
        p2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 70));

        panles_resporteMateriales.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 540, 70));

        btm_generar.setBackground(new java.awt.Color(0, 0, 0));
        btm_generar.setForeground(new java.awt.Color(255, 255, 255));
        btm_generar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar_icono.png"))); // NOI18N
        btm_generar.setText("Generar");
        btm_generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_generarActionPerformed(evt);
            }
        });
        panles_resporteMateriales.add(btm_generar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 144, 35));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        panles_resporteMateriales.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 240));

        jTabbedPane1.addTab("Reportes Materiales", panles_resporteMateriales);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tipo de Reporte:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 27, -1, -1));

        cmbtipodereporte_devoluciones.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmbtipodereporte_devoluciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Consultar Por Documento", "Consultar por Documento + Fechas" }));
        cmbtipodereporte_devoluciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmbtipodereporte_devoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtipodereporte_devolucionesActionPerformed(evt);
            }
        });
        jPanel4.add(cmbtipodereporte_devoluciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 22, 277, -1));

        btm_generar__devoluciones.setBackground(new java.awt.Color(0, 0, 0));
        btm_generar__devoluciones.setForeground(new java.awt.Color(255, 255, 255));
        btm_generar__devoluciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar_icono.png"))); // NOI18N
        btm_generar__devoluciones.setText("Generar");
        btm_generar__devoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_generar__devolucionesActionPerformed(evt);
            }
        });
        jPanel4.add(btm_generar__devoluciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 18, 144, 35));

        consultar_por_documento_mas_fechas.setBackground(new java.awt.Color(255, 255, 255));
        consultar_por_documento_mas_fechas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Colsultar Por Documento + Fechas:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 14))); // NOI18N
        consultar_por_documento_mas_fechas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        doc_devoluciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        doc_devoluciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                doc_devolucionesKeyTyped(evt);
            }
        });
        consultar_por_documento_mas_fechas.add(doc_devoluciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 40, 180, 24));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel10.setText("Fecha Inicial:");
        consultar_por_documento_mas_fechas.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel11.setText("Ingrese Documento");
        consultar_por_documento_mas_fechas.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 20, -1, -1));

        f_inicial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        consultar_por_documento_mas_fechas.add(f_inicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 20, 144, -1));

        f_final.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        consultar_por_documento_mas_fechas.add(f_final, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 58, 144, -1));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel12.setText("Fecha Final:");
        consultar_por_documento_mas_fechas.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 58, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        consultar_por_documento_mas_fechas.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 90));

        jPanel4.add(consultar_por_documento_mas_fechas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 540, 90));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -16, 650, 330));

        jTabbedPane1.addTab("Reportes Devoluciones", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btm_generar__deudores.setBackground(new java.awt.Color(0, 0, 0));
        btm_generar__deudores.setForeground(new java.awt.Color(255, 255, 255));
        btm_generar__deudores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar_icono.png"))); // NOI18N
        btm_generar__deudores.setText("Generar Lista Deudores");
        btm_generar__deudores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_generar__deudoresActionPerformed(evt);
            }
        });
        jPanel5.add(btm_generar__deudores, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 208, -1));

        fecha_actual2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(fecha_actual2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 140, 30));

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel23.setText("Ingrese Fecha Actual");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jTextPane1.setText("Los usuarios que se encuentran en esta lista, deben de pagar sus deudas lo mas pronto posible");
        jScrollPane4.setViewportView(jTextPane1);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 240, 150));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -16, 650, 260));

        jTabbedPane1.addTab("Deudores Morosos", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Ingrese Nombre de Editorial");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        cmbsegun.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmbsegun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Tipo", "Editorial" }));
        cmbsegun.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmbsegun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbsegunActionPerformed(evt);
            }
        });
        jPanel6.add(cmbsegun, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 118, -1));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tipo:");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        cmbtipo_material.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmbtipo_material.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Libro", "Revista", "Tesis" }));
        cmbtipo_material.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmbtipo_material.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtipo_materialActionPerformed(evt);
            }
        });
        jPanel6.add(cmbtipo_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 118, -1));

        btm_generar_material.setBackground(new java.awt.Color(0, 0, 0));
        btm_generar_material.setForeground(new java.awt.Color(255, 255, 255));
        btm_generar_material.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar_icono.png"))); // NOI18N
        btm_generar_material.setText("Generar Lista");
        btm_generar_material.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_generar_materialActionPerformed(evt);
            }
        });
        jPanel6.add(btm_generar_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 208, -1));

        jLabel25.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Listado De Material Segun:");
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        nombre_editorial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(nombre_editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 180, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -16, 650, 330));

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Tipo:");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        jTabbedPane1.addTab("Material Segun", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmb_usuario_segun.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmb_usuario_segun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Estudiante", "Profesor", "Externo" }));
        cmb_usuario_segun.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmb_usuario_segun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_usuario_segunActionPerformed(evt);
            }
        });
        jPanel7.add(cmb_usuario_segun, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 118, -1));

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Listado De Usuario Segun:");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        btm_generar_usuarios.setBackground(new java.awt.Color(0, 0, 0));
        btm_generar_usuarios.setForeground(new java.awt.Color(255, 255, 255));
        btm_generar_usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar_icono.png"))); // NOI18N
        btm_generar_usuarios.setText("Generar Lista");
        btm_generar_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_generar_usuariosActionPerformed(evt);
            }
        });
        jPanel7.add(btm_generar_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 208, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -16, 650, 330));

        jTabbedPane1.addTab("Usuarios", jPanel7);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 650, 270));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_reportes.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbtipodereporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtipodereporteActionPerformed
        switch (cmbtipodereporte.getSelectedIndex()) {
            case 1:
                p2.setVisible(true);
                m_fecha_final.setVisible(false);
                m_fecha_inicial.setVisible(false);
                jLabel5.setVisible(false);
                jLabel7.setVisible(false);
                btm_generar.setVisible(true);
                break;
            case 2:

                m_fecha_final.setVisible(true);
                m_fecha_inicial.setVisible(true);
                jLabel5.setVisible(true);
                jLabel7.setVisible(true);
                break;
            case 0:

                p2.setVisible(false);
                btm_generar.setVisible(false);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_cmbtipodereporteActionPerformed

    private void cmbtipodereporte_devolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtipodereporte_devolucionesActionPerformed
        switch (cmbtipodereporte_devoluciones.getSelectedIndex()) {
            case 1:
                consultar_por_documento_mas_fechas.setVisible(true);
                doc_devoluciones.setVisible(true);
                f_final.setVisible(false);
                f_inicial.setVisible(false);
                jLabel10.setVisible(false);
                jLabel12.setVisible(false);
                btm_generar__devoluciones.setVisible(true);
                break;
            case 2:
                consultar_por_documento_mas_fechas.setVisible(true);
                f_final.setVisible(true);
                f_inicial.setVisible(true);
                jLabel10.setVisible(true);
                jLabel12.setVisible(true);
                btm_generar__devoluciones.setVisible(true);
                break;
            case 0:

                consultar_por_documento_mas_fechas.setVisible(false);
                btm_generar__devoluciones.setVisible(false);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_cmbtipodereporte_devolucionesActionPerformed

    private void cmbsegunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbsegunActionPerformed

//       modelo.addElement("lista");
//       list_edito.setModel(modelo);
        switch (cmbsegun.getSelectedIndex()) {
            case 0:
                jLabel13.setVisible(false);
                cmbtipo_material.setEnabled(false);
                nombre_editorial.setVisible(false);
                break;
            case 1:
                jLabel13.setVisible(false);
                nombre_editorial.setVisible(false);
                cmbtipo_material.setEnabled(true);
                break;
            case 2:
                jLabel13.setVisible(true);
                nombre_editorial.setVisible(true);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_cmbsegunActionPerformed

    private void cmbtipo_materialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtipo_materialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtipo_materialActionPerformed

    private void cmb_usuario_segunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_usuario_segunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_usuario_segunActionPerformed

    private void btm_listado_materialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_listado_materialesActionPerformed
        Metodos.Metodos.generar_reporte_materiales();
    }//GEN-LAST:event_btm_listado_materialesActionPerformed

    private void btm_listado_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_listado_usuariosActionPerformed
        Metodos.Metodos.generar_reporte_usuarios();
    }//GEN-LAST:event_btm_listado_usuariosActionPerformed

    private void btm_listado_alumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_listado_alumnosActionPerformed
        Abstracciones.Abs_alumnos_x_semestre.generar_reporte_alumnos();
    }//GEN-LAST:event_btm_listado_alumnosActionPerformed

    private void btm_listado_prestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_listado_prestamosActionPerformed
        Metodos.Metodos.generar_reporte_prestamos();
    }//GEN-LAST:event_btm_listado_prestamosActionPerformed

    private void btm_listado_devolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_listado_devolucionesActionPerformed
        Metodos.Metodos.generar_reporte_devoluciones();
    }//GEN-LAST:event_btm_listado_devolucionesActionPerformed

    private void btm_generar__deudoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_generar__deudoresActionPerformed

        if (fecha_actual2.getDate() != null) {
            LinkedList<Abstracciones.Abs_deudores> Lista_dudores = new LinkedList<>();
            Date fecha_actual = fecha_actual2.getDate();
            for (Abstracciones.Abs_prestamo d : Metodos.Metodos.lista_prestamo) {

                if (!"ENTREGADO".equals(d.getEstado())) {
                    int dias_diferencia = Metodos.Metodos.diferencia_dias_fecha(fecha_actual, d.getFecha_entrega());
                    if (dias_diferencia >= 1) {
                        int multa = dias_diferencia * 1000;
                        Lista_dudores.add(new Abs_deudores(d.getId_prestamo(), d.getId_usuario(), d.getId_material(),
                                dias_diferencia, "$" + Integer.toString(multa)));
                    }
                }
            }

            try {
                JasperReport jp = (JasperReport) JRLoader.loadObject(new FileInputStream("src/Reportes/Rlista_deudores.jasper"));
                @SuppressWarnings("unchecked")
                Map<String, Object> parametros = new HashMap();
                parametros.put("logo", parametros.getClass().getResourceAsStream(link_reportes));
                JasperPrint prin = JasperFillManager.fillReport(jp, parametros, new JRBeanCollectionDataSource(Lista_dudores));
                JasperViewer.viewReport(prin, false);

            } catch (FileNotFoundException | JRException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "POR FAVOR INGRESE LA FECHA DE HOY");
        }

    }//GEN-LAST:event_btm_generar__deudoresActionPerformed

    private void btm_generar_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_generar_usuariosActionPerformed
        LinkedList<Abstracciones.Abs_usuario> lista_tipo_usuario = new LinkedList<>();
        switch (cmb_usuario_segun.getSelectedIndex()) {
            case 0:
                JOptionPane.showMessageDialog(null, "POR FAVOR SELECCIONE TIPO");
                break;
            case 1:

                for (Abstracciones.Abs_usuario d : Metodos.Metodos.Lista_usuarios) {
                    if (d.getRol() == 1) {
                        lista_tipo_usuario.add(new Abs_usuario(d.getId_usuario(), d.getNombre(), d.getRol(), d.getTelefono()));
                    }
                }
                try {
                    JasperReport jp = (JasperReport) JRLoader.loadObject(new FileInputStream("src/Reportes/Rlista_Usuarios_tipo.jasper"));
                    @SuppressWarnings("unchecked")
                    Map<String, Object> parametros = new HashMap();
                    parametros.put("logo", parametros.getClass().getResourceAsStream(link_reportes));
                    parametros.put("tipo", "Estudiantes");
                    JasperPrint prin = JasperFillManager.fillReport(jp, parametros, new JRBeanCollectionDataSource(lista_tipo_usuario));
                    JasperViewer.viewReport(prin, false);

                } catch (FileNotFoundException | JRException e) {
                    JOptionPane.showMessageDialog(null, e);
                }

                break;
            case 2:

                for (Abstracciones.Abs_usuario d : Metodos.Metodos.Lista_usuarios) {
                    if (d.getRol() == 2) {
                        lista_tipo_usuario.add(new Abs_usuario(d.getId_usuario(), d.getNombre(), d.getRol(), d.getTelefono()));
                    }
                }
                try {
                    JasperReport jp = (JasperReport) JRLoader.loadObject(new FileInputStream("src/Reportes/Rlista_Usuarios_tipo.jasper"));
                    @SuppressWarnings("unchecked")
                    Map<String, Object> parametros = new HashMap();
                    parametros.put("logo", parametros.getClass().getResourceAsStream(link_reportes));
                    parametros.put("tipo", "Docentes");
                    JasperPrint prin = JasperFillManager.fillReport(jp, parametros, new JRBeanCollectionDataSource(lista_tipo_usuario));
                    JasperViewer.viewReport(prin, false);

                } catch (FileNotFoundException | JRException e) {
                    JOptionPane.showMessageDialog(null, e);
                }

                break;
            case 3:

                for (Abstracciones.Abs_usuario d : Metodos.Metodos.Lista_usuarios) {
                    if (d.getRol() == 3) {
                        lista_tipo_usuario.add(new Abs_usuario(d.getId_usuario(), d.getNombre(), d.getRol(), d.getTelefono()));
                    }
                }
                try {
                    JasperReport jp = (JasperReport) JRLoader.loadObject(new FileInputStream("src/Reportes/Rlista_Usuarios_tipo.jasper"));
                    @SuppressWarnings("unchecked")
                    Map<String, Object> parametros = new HashMap();
                    parametros.put("logo", parametros.getClass().getResourceAsStream(link_reportes));
                    parametros.put("tipo", "Externos");
                    JasperPrint prin = JasperFillManager.fillReport(jp, parametros, new JRBeanCollectionDataSource(lista_tipo_usuario));
                    JasperViewer.viewReport(prin, false);

                } catch (FileNotFoundException | JRException e) {
                    JOptionPane.showMessageDialog(null, e);
                }

                break;
            default:
                break;
        }
    }//GEN-LAST:event_btm_generar_usuariosActionPerformed

    private void btm_generar_materialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_generar_materialActionPerformed
        LinkedList<Abstracciones.Abs_material> lis_temp_material = new LinkedList<>();
        switch (cmbsegun.getSelectedIndex()) {
            case 0:
                JOptionPane.showMessageDialog(null, "POR FAVOR SELECCIONE SEGUN MATERIAL");
                break;
            case 1:
                switch (cmbtipo_material.getSelectedIndex()) {
                    case 0:
                        JOptionPane.showMessageDialog(null, "POR FAVOR SELECCIONE UN TIPO");
                        break;
                    case 1:
                        for (Abstracciones.Abs_material d : Metodos.Metodos.lista_materiales) {
                            if (d.getTipo() == 1) {
                                lis_temp_material.add(new Abs_material(d.getId_material(), d.getNombre(), d.getTipo(), d.getEditorial(), d.getCantidad()));
                            }
                        }
                        try {
                            JasperReport jp = (JasperReport) JRLoader.loadObject(new FileInputStream("src/Reportes/Rlista_materiales.jasper"));
                            @SuppressWarnings("unchecked")
                            Map<String, Object> parametros = new HashMap();
                            parametros.clear();
                            parametros.put("logo", parametros.getClass().getResourceAsStream(link_reportes));
                            JasperPrint prin = JasperFillManager.fillReport(jp, parametros, new JRBeanCollectionDataSource(lis_temp_material));
                            JasperViewer.viewReport(prin, false);

                        } catch (FileNotFoundException | JRException e) {
                            JOptionPane.showMessageDialog(null, e);
                        }
                        break;
                    case 2:
                        for (Abstracciones.Abs_material d : Metodos.Metodos.lista_materiales) {
                            if (d.getTipo() == 2) {
                                lis_temp_material.add(new Abs_material(d.getId_material(), d.getNombre(), d.getTipo(), d.getEditorial(), d.getCantidad()));
                            }
                        }
                        try {
                            JasperReport jp = (JasperReport) JRLoader.loadObject(new FileInputStream("src/Reportes/Rlista_materiales.jasper"));
                            @SuppressWarnings("unchecked")
                            Map<String, Object> parametros = new HashMap();
                            parametros.clear();
                            parametros.put("logo", parametros.getClass().getResourceAsStream(link_reportes));
                            JasperPrint prin = JasperFillManager.fillReport(jp, parametros, new JRBeanCollectionDataSource(lis_temp_material));
                            JasperViewer.viewReport(prin, false);

                        } catch (FileNotFoundException | JRException e) {
                            JOptionPane.showMessageDialog(null, e);
                        }

                        break;
                    case 3:
                        for (Abstracciones.Abs_material d : Metodos.Metodos.lista_materiales) {
                            if (d.getTipo() == 3) {
                                lis_temp_material.add(new Abs_material(d.getId_material(), d.getNombre(), d.getTipo(), d.getEditorial(), d.getCantidad()));
                            }
                        }
                        try {
                            JasperReport jp = (JasperReport) JRLoader.loadObject(new FileInputStream("src/Reportes/Rlista_materiales.jasper"));
                            @SuppressWarnings("unchecked")
                            Map<String, Object> parametros = new HashMap();
                            parametros.clear();
                            parametros.put("logo", parametros.getClass().getResourceAsStream(link_reportes));
                            JasperPrint prin = JasperFillManager.fillReport(jp, parametros, new JRBeanCollectionDataSource(lis_temp_material));
                            JasperViewer.viewReport(prin, false);

                        } catch (FileNotFoundException | JRException e) {
                            JOptionPane.showMessageDialog(null, e);
                        }

                        break;
                }
                break;
            case 2:
                if (!nombre_editorial.getText().isEmpty()) {
                    String editorial = nombre_editorial.getText().trim();
                    for (Abstracciones.Abs_material d : Metodos.Metodos.lista_materiales) {
                        if (d.getEditorial().equals(editorial)) {
                            lis_temp_material.add(new Abs_material(d.getId_material(), d.getNombre(), d.getTipo(), d.getEditorial(), d.getCantidad()));
                        }
                    }
                    if (lis_temp_material.isEmpty()) {
                        JOptionPane.showMessageDialog(null, "EDITOIAL NO ENCONTRADA");
                    } else {
                        try {
                            JasperReport jp = (JasperReport) JRLoader.loadObject(new FileInputStream("src/Reportes/Rlista_materiales.jasper"));
                            @SuppressWarnings("unchecked")
                            Map<String, Object> parametros = new HashMap();
                            parametros.clear();
                            parametros.put("logo", parametros.getClass().getResourceAsStream(link_reportes));
                            JasperPrint prin = JasperFillManager.fillReport(jp, parametros, new JRBeanCollectionDataSource(lis_temp_material));
                            JasperViewer.viewReport(prin, false);

                        } catch (FileNotFoundException | JRException e) {
                            JOptionPane.showMessageDialog(null, e);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "INGRESE EDITORIAL");
                }

                break;
        }
    }//GEN-LAST:event_btm_generar_materialActionPerformed

    private void btm_generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_generarActionPerformed

        LinkedList<Abstracciones.Abs_prestamo> lista_p_doc = new LinkedList<>();
        switch (cmbtipodereporte.getSelectedIndex()) {
            case 0:
                JOptionPane.showMessageDialog(null, "POR FAVOR SELECCIONE TIPO");
                break;
            case 1:
                if (!tdoc_materiales.getText().isEmpty()) {

                    long documento = Long.parseLong(tdoc_materiales.getText());
                    for (Abstracciones.Abs_prestamo d : Metodos.Metodos.lista_prestamo) {
                        if (documento == d.getId_usuario()) {
                            lista_p_doc.add(new Abs_prestamo(d.getId_prestamo(), d.getId_usuario(), d.getId_material(), d.getFecha_prestamo(), d.getFecha_entrega(), d.getEstado()));

                        }
                    }

                    try {
                        JasperReport jp = (JasperReport) JRLoader.loadObject(new FileInputStream("src/Reportes/Rlista_prestamos.jasper"));
                        @SuppressWarnings("unchecked")
                        Map<String, Object> parametros = new HashMap();
                        parametros.put("logo", parametros.getClass().getResourceAsStream(link_reportes));
                        JasperPrint prin = JasperFillManager.fillReport(jp, parametros, new JRBeanCollectionDataSource(lista_p_doc));
                        JasperViewer.viewReport(prin, false);

                    } catch (FileNotFoundException | JRException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "INGRESE DOCUMENTO");
                }
                break;

            case 2:
                if (!tdoc_materiales.getText().isEmpty()) {
                    if (m_fecha_inicial.getDate() != null) {
                        if (m_fecha_final.getDate() != null) {
                            long documento = Long.parseLong(tdoc_materiales.getText());
                            SimpleDateFormat fecha = new SimpleDateFormat("dd/MM/yyyy");
                            //convertir el mismo formato por del del archivo plano
                            String fecha_i = new SimpleDateFormat("dd/MM/yyyy").format(m_fecha_inicial.getDate());
                            String fecha_f = new SimpleDateFormat("dd/MM/yyyy").format(m_fecha_final.getDate());

                            for (Abs_prestamo d : Metodos.Metodos.lista_prestamo) {

                                try {
                                    Date fecha_ini = fecha.parse(fecha_i);
                                    Date fecha_fin = fecha.parse(fecha_f);

                                    //comparo fecha
                                    if (d.getFecha_prestamo().compareTo(fecha_ini) >= 0 && d.getFecha_prestamo().compareTo(fecha_fin) <= 0 && d.getId_usuario() == documento) {

                                        lista_p_doc.add(new Abs_prestamo(d.getId_prestamo(), d.getId_usuario(), d.getId_material(), d.getFecha_prestamo(), d.getFecha_entrega(), d.getEstado()));
                                    }

                                } catch (ParseException ex) {
                                    Logger.getLogger(FReportes.class.getName()).log(Level.SEVERE, null, ex);
                                }

                            }
                            try {
                                JasperReport jp = (JasperReport) JRLoader.loadObject(new FileInputStream("src/Reportes/Rlista_prestamos.jasper"));
                                @SuppressWarnings("unchecked")
                                Map<String, Object> parametros = new HashMap();
                                parametros.put("logo", parametros.getClass().getResourceAsStream(link_reportes));
                                JasperPrint prin = JasperFillManager.fillReport(jp, parametros, new JRBeanCollectionDataSource(lista_p_doc));
                                JasperViewer.viewReport(prin, false);

                            } catch (FileNotFoundException | JRException e) {
                                JOptionPane.showMessageDialog(null, e);
                            }
                            m_fecha_final.setDate(null);
                            m_fecha_inicial.setDate(null);

                        } else {
                            JOptionPane.showMessageDialog(null, "INGRESE FECHA FINAL");
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "INGRESE FECHA INICIAL");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "INGRESE DOCUMENTO");
                }

                break;

            default:
                break;

        }
    }//GEN-LAST:event_btm_generarActionPerformed

    private void btm_generar__devolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_generar__devolucionesActionPerformed
        LinkedList<Abstracciones.Abs_devoluciones> lista_d_doc = new LinkedList<>();
        switch (cmbtipodereporte_devoluciones.getSelectedIndex()) {
            case 0:
                JOptionPane.showMessageDialog(null, "POR FAVOR SELECCIONE TIPO");
                break;
            case 1:
                if (!doc_devoluciones.getText().isEmpty()) {

                    long documento = Long.parseLong(doc_devoluciones.getText());
                    for (Abstracciones.Abs_devoluciones d : Metodos.Metodos.lista_devoluciones) {
                        if (documento == d.getId_usuario()) {
                            lista_d_doc.add(new Abs_devoluciones(d.getId_devolucion(), d.getId_usuario(), d.getId_material(), d.getFecha_devolucion()));

                        }
                    }

                    try {
                        JasperReport jp = (JasperReport) JRLoader.loadObject(new FileInputStream("src/Reportes/Rlista_devoluciones.jasper"));
                        @SuppressWarnings("unchecked")
                        Map<String, Object> parametros = new HashMap();
                        parametros.put("logo", parametros.getClass().getResourceAsStream(link_reportes));
                        JasperPrint prin = JasperFillManager.fillReport(jp, parametros, new JRBeanCollectionDataSource(lista_d_doc));
                        JasperViewer.viewReport(prin, false);

                    } catch (FileNotFoundException | JRException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "INGRESE DOCUMENTO");
                }
                break;

            case 2:
                if (!doc_devoluciones.getText().isEmpty()) {
                    if (f_inicial.getDate() != null) {
                        if (f_final.getDate() != null) {
                            long documento = Long.parseLong(doc_devoluciones.getText());
                            SimpleDateFormat fecha = new SimpleDateFormat("dd/MM/yyyy");
                            //convertir el mismo formato por del del archivo plano
                            String fecha_i = new SimpleDateFormat("dd/MM/yyyy").format(f_inicial.getDate());
                            String fecha_f = new SimpleDateFormat("dd/MM/yyyy").format(f_final.getDate());

                            for (Abs_devoluciones d : Metodos.Metodos.lista_devoluciones) {
                                System.out.println("ssss");
                                try {
                                    Date fecha_ini = fecha.parse(fecha_i);
                                    Date fecha_fin = fecha.parse(fecha_f);

                                    //comparo fecha
                                    if (d.getFecha_devolucion().compareTo(fecha_ini) >= 0 && d.getFecha_devolucion().compareTo(fecha_fin) <= 0 && d.getId_usuario() == documento) {

                                        lista_d_doc.add(new Abs_devoluciones(d.getId_devolucion(), d.getId_usuario(), d.getId_material(), d.getFecha_devolucion()));
                                    }

                                } catch (ParseException ex) {
                                    Logger.getLogger(FReportes.class.getName()).log(Level.SEVERE, null, ex);
                                }

                            }
                            try {
                                JasperReport jp = (JasperReport) JRLoader.loadObject(new FileInputStream("src/Reportes/Rlista_devoluciones.jasper"));
                                @SuppressWarnings("unchecked")
                                Map<String, Object> parametros = new HashMap();
                                parametros.put("logo", parametros.getClass().getResourceAsStream(link_reportes));
                                JasperPrint prin = JasperFillManager.fillReport(jp, parametros, new JRBeanCollectionDataSource(lista_d_doc));
                                JasperViewer.viewReport(prin, false);

                            } catch (FileNotFoundException | JRException e) {
                                JOptionPane.showMessageDialog(null, e);
                            }
                            f_final.setDate(null);
                            f_inicial.setDate(null);

                        } else {
                            JOptionPane.showMessageDialog(null, "INGRESE FECHA FINAL");
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "INGRESE FECHA INICIAL");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "INGRESE DOCUMENTO");
                }

                break;

            default:
                break;

        }
    }//GEN-LAST:event_btm_generar__devolucionesActionPerformed

    private void tdoc_materialesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tdoc_materialesKeyTyped
        char teclaseleccionada = evt.getKeyChar();
        if (Character.isLetter(teclaseleccionada)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "SOLO SE PUEDEN INGRESAR NUMEROS EN EL CAMPO");
        }
    }//GEN-LAST:event_tdoc_materialesKeyTyped

    private void doc_devolucionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_doc_devolucionesKeyTyped
       char teclaseleccionada = evt.getKeyChar();
        if (Character.isLetter(teclaseleccionada)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "SOLO SE PUEDEN INGRESAR NUMEROS EN EL CAMPO");
        }
    }//GEN-LAST:event_doc_devolucionesKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_listados;
    private javax.swing.JButton btm_generar;
    private javax.swing.JButton btm_generar__deudores;
    private javax.swing.JButton btm_generar__devoluciones;
    private javax.swing.JButton btm_generar_material;
    private javax.swing.JButton btm_generar_usuarios;
    private javax.swing.JButton btm_listado_alumnos;
    private javax.swing.JButton btm_listado_devoluciones;
    private javax.swing.JButton btm_listado_materiales;
    private javax.swing.JButton btm_listado_prestamos;
    private javax.swing.JButton btm_listado_usuarios;
    private javax.swing.JComboBox<String> cmb_usuario_segun;
    private javax.swing.JComboBox<String> cmbsegun;
    private javax.swing.JComboBox<String> cmbtipo_material;
    private javax.swing.JComboBox<String> cmbtipodereporte;
    private javax.swing.JComboBox<String> cmbtipodereporte_devoluciones;
    private javax.swing.JPanel consultar_por_documento_mas_fechas;
    private javax.swing.JTextField doc_devoluciones;
    private com.toedter.calendar.JDateChooser f_final;
    private com.toedter.calendar.JDateChooser f_inicial;
    private com.toedter.calendar.JDateChooser fecha_actual2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextPane1;
    private com.toedter.calendar.JDateChooser m_fecha_final;
    private com.toedter.calendar.JDateChooser m_fecha_inicial;
    private javax.swing.JTextField nombre_editorial;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel panles_resporteMateriales;
    private javax.swing.JTextField tdoc_materiales;
    // End of variables declaration//GEN-END:variables
}
