/*
 * Este codigo fue creado por @DuvanBotello
 *  <"Sin lógica no hay paraíso">
 */
package GUI;

import java.awt.event.KeyEvent;
import java.util.Iterator;
import Abstracciones.*;
import java.awt.Color;
//import java.awt.Color;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

/**
 *
 * @author DuvanBotello
 * <http://yoaprendo-informatica.blogspot.com.co/ - duvanbotello1008@gmail.com>
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    int x, y;

    public Login() {
        initComponents();

//        AWTUtilities.setWindowOpaque(this, false);
        cargar_cosas();

        fondo();
    }

    private void fondo() {
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
        Metodos.Metodos.icono_proyecto(this);
    }

    private void cargar_cosas() {
        if (Metodos.Metodos.Lista_usuarios.isEmpty()) {

            Metodos.Metodos.CargarLista_Usuarios();

        }
        if (Metodos.Metodos.lista_devoluciones.isEmpty()) {

            Metodos.Metodos.CargarLista_Devoluciones();

        }
        if (Metodos.Metodos.lista_materiales.isEmpty()) {
            Metodos.Metodos.CargarLista_Materiales();
        }

        if (Abs_Empleado.lista_rempleados.isEmpty()) {
            Abstracciones.Abs_Empleado.CargarLista_Empleados();
        }
        if (Abs_alumnos_x_semestre.lista_alumnos_x_semestre.isEmpty()) {
            Abs_alumnos_x_semestre.CargarLista_Alumnos();
        }
        if (Metodos.Metodos.lista_prestamo.isEmpty()) {
            Metodos.Metodos.CargarLista_prestamos();
        }

        Abstracciones.Abs_Empleado.crer_txtempleados();
        Metodos.Metodos.Crear_Archivos();
        Abs_alumnos_x_semestre.crer_txtAlumnos_semestre();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtusuario = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        lb_mover = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btmsalir = new javax.swing.JButton();
        btminiciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtusuario.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtusuario.setBorder(null);
        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        txtusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusuarioKeyTyped(evt);
            }
        });
        getContentPane().add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 190, 30));

        txtpass.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtpass.setBorder(null);
        txtpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpassKeyTyped(evt);
            }
        });
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 190, 20));

        lb_mover.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        lb_mover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lb_moverMouseDragged(evt);
            }
        });
        lb_mover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lb_moverMousePressed(evt);
            }
        });
        getContentPane().add(lb_mover, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 210, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("--------------------------------------------------------");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        btmsalir.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btmsalir.setForeground(new java.awt.Color(255, 255, 255));
        btmsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btm_imagen.png"))); // NOI18N
        btmsalir.setText("Salir");
        btmsalir.setBorder(null);
        btmsalir.setBorderPainted(false);
        btmsalir.setContentAreaFilled(false);
        btmsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btmsalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btmsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btmsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 90, -1));

        btminiciar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btminiciar.setForeground(new java.awt.Color(255, 255, 255));
        btminiciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btm_imagen.png"))); // NOI18N
        btminiciar.setText("Iniciar");
        btminiciar.setBorder(null);
        btminiciar.setBorderPainted(false);
        btminiciar.setContentAreaFilled(false);
        btminiciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btminiciar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btminiciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btminiciarActionPerformed(evt);
            }
        });
        getContentPane().add(btminiciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb_moverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_moverMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_lb_moverMousePressed

    private void lb_moverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_moverMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_lb_moverMouseDragged

    private void btmsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btmsalirActionPerformed

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed

    }//GEN-LAST:event_txtusuarioActionPerformed

    private void txtusuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusuarioKeyTyped
        char teclaseleccionada = evt.getKeyChar();
        if (teclaseleccionada == KeyEvent.VK_ENTER || teclaseleccionada == KeyEvent.VK_I) {
            btminiciar.doClick();
        }
    }//GEN-LAST:event_txtusuarioKeyTyped

    private void txtpassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyTyped
        char teclaseleccionada = evt.getKeyChar();
        if (teclaseleccionada == KeyEvent.VK_ENTER || teclaseleccionada == KeyEvent.VK_I) {
            btminiciar.doClick();
        }
    }//GEN-LAST:event_txtpassKeyTyped

    private void btminiciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btminiciarActionPerformed
        char[] arrayC = txtpass.getPassword();
        String pass = new String(arrayC);
        if (!txtusuario.getText().isEmpty()) {
            if (!pass.isEmpty()) {

                long documento = Long.parseLong(txtusuario.getText().trim());
                String contraseña = pass.trim();
                boolean existeu = false;
                Abs_Empleado d;
                Iterator<Abs_Empleado> buscar = Abs_Empleado.lista_rempleados.iterator();
                for (int i = 0; i < Abs_Empleado.lista_rempleados.size(); i++) {
                    d = buscar.next();
                    if (documento == d.getId_usuario()) {
                        existeu = true;
                        if (contraseña.equals(d.getContraseña())) {

                            Principal f = new Principal();
                            f.setVisible(true);
                            Principal.pusuario.setText(Long.toString(d.getId_usuario()));
                            Principal.pnombre.setText(d.getNombre());
                            if (d.getRol() == 1) {
                                Principal.ttipo.setText("Administrador");
                            }
                            if (d.getRol() == 2) {
                                Principal.ttipo.setText("Empleado");
                            }
                            Principal.ttelefono.setText(Integer.toString(d.getTelefono()));
                            StringTokenizer mistokens = new StringTokenizer(d.getNombre(), " ");
                            String lb = mistokens.nextToken().trim();
                            Principal.lbbienvenida.setText("BIENVENID@, @" + lb);
                            this.dispose();
                            break;
                        } else {
                            JOptionPane.showMessageDialog(null, "Contraseña Incorrecta");
                            break;
                        }
                    }
                }
                if (existeu == false) {
                    JOptionPane.showMessageDialog(null, "Usuario Incorrecto");
                    txtpass.setText("");
                    txtusuario.setText("");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Digite Contraseña");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Ingrese Usuario");
        }
    }//GEN-LAST:event_btminiciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btminiciar;
    private javax.swing.JButton btmsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lb_mover;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
