/*
 * Este codigo fue creado por @DuvanBotello
 *  <"Sin lógica no hay paraíso">
 */
package GUI;

import Abstracciones.Abs_devoluciones;
import Abstracciones.Abs_material;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author DuvanBotello
 * <http://yoaprendo-informatica.blogspot.com.co/ - duvanbotello1008@gmail.com>
 */
public class R_devoluciones extends javax.swing.JFrame {

    DefaultTableModel modelo_devoluciones = new DefaultTableModel();
    private TableRowSorter<TableModel> trs;

    /**
     * Creates new form R_devoluciones
     */
    public R_devoluciones() {

        initComponents();
        Metodos.Metodos.icono_proyecto(this);
        this.setLocationRelativeTo(null);
       
        modelo_devoluciones.addColumn("ID PRESTAMO");
        modelo_devoluciones.addColumn("ID USUARIO");
        modelo_devoluciones.addColumn("ID MATERIAL");
        modelo_devoluciones.addColumn("ID FECHA_PRESTAMO");
        modelo_devoluciones.addColumn("ID FECHA_ENTREGA");
        modelo_devoluciones.addColumn("ID ESTADO");
        tb_devoluciones.setModel(modelo_devoluciones);
        cargartabla_devolciones();

    }

    private void cargartabla_devolciones() {
        modelo_devoluciones.setRowCount(0);
        Iterator<Abstracciones.Abs_prestamo> buscar2 = Metodos.Metodos.lista_prestamo.iterator();
        Object file[] = new Object[tb_devoluciones.getColumnCount()];
        for (Abstracciones.Abs_prestamo d : Metodos.Metodos.lista_prestamo) {
            d = buscar2.next();
            String fecha = new SimpleDateFormat("dd/MM/yyyy").format(d.getFecha_prestamo());
            String fecha1 = new SimpleDateFormat("dd/MM/yyyy").format(d.getFecha_entrega());
            file[0] = d.getId_prestamo();
            file[1] = d.getId_usuario();
            file[2] = d.getId_material();
            file[3] = fecha;
            file[4] = fecha1;
            file[5] = d.getEstado();
            modelo_devoluciones.addRow(file);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        btm_validar = new javax.swing.JButton();
        txt_idprestamo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_idmaterial = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_fecha_prestamo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_fecha_entrega = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        fecha_Actual = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_devoluciones = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txt_buscar_documento = new javax.swing.JTextField();
        cbm_buscar = new javax.swing.JComboBox<>();
        fecha_prestamo = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        btmbuscar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DEVOLUCION DE MATERIAL - BIBLIOETECA UNIPAMPLONA");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos de Devolucion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 12))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USUARIO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        txt_usuario.setEditable(false);
        txt_usuario.setBackground(new java.awt.Color(0, 204, 204));
        txt_usuario.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txt_usuario.setForeground(new java.awt.Color(255, 0, 0));
        txt_usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_usuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 150, 20));

        btm_validar.setBackground(new java.awt.Color(0, 0, 0));
        btm_validar.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btm_validar.setForeground(new java.awt.Color(255, 255, 255));
        btm_validar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ico_validar.png"))); // NOI18N
        btm_validar.setText("Validar Entrega");
        btm_validar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_validarActionPerformed(evt);
            }
        });
        jPanel1.add(btm_validar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 180, 50));

        txt_idprestamo.setEditable(false);
        txt_idprestamo.setBackground(new java.awt.Color(0, 204, 204));
        txt_idprestamo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txt_idprestamo.setForeground(new java.awt.Color(255, 0, 0));
        txt_idprestamo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_idprestamo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_idprestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 150, 20));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID DE PRESTAMO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        txt_idmaterial.setEditable(false);
        txt_idmaterial.setBackground(new java.awt.Color(0, 204, 204));
        txt_idmaterial.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txt_idmaterial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_idmaterial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_idmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 150, 20));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("FECHA DE PRESTAMO");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txt_fecha_prestamo.setEditable(false);
        txt_fecha_prestamo.setBackground(new java.awt.Color(0, 204, 204));
        txt_fecha_prestamo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txt_fecha_prestamo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fecha_prestamo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_fecha_prestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 110, 20));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ID DE MATERIAL");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 0));
        jLabel11.setText("FECHA DE ACTUAL :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        txt_fecha_entrega.setEditable(false);
        txt_fecha_entrega.setBackground(new java.awt.Color(0, 204, 204));
        txt_fecha_entrega.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txt_fecha_entrega.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fecha_entrega.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_fecha_entrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 110, 20));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("FECHA DE ENTREGA");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        fecha_Actual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(fecha_Actual, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 150, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 160));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 550, 160));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Buscar Prestamo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_devoluciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_devoluciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_devolucionesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_devoluciones);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 620, 150));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Documento Usuario");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        txt_buscar_documento.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        txt_buscar_documento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_buscar_documento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_buscar_documentoKeyTyped(evt);
            }
        });
        jPanel2.add(txt_buscar_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 150, 20));

        cbm_buscar.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        cbm_buscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Segun:", "Documento", "Documento + Fecha" }));
        cbm_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbm_buscarActionPerformed(evt);
            }
        });
        jPanel2.add(cbm_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 150, -1));
        jPanel2.add(fecha_prestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 140, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Buscar:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btmbuscar.setBackground(new java.awt.Color(0, 0, 0));
        btmbuscar.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btmbuscar.setForeground(new java.awt.Color(255, 255, 255));
        btmbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_buscar.png"))); // NOI18N
        btmbuscar.setText("Buscar");
        btmbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmbuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btmbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 140, 60));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha de Prestamo");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 250));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 650, 250));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_devoluciones.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_devolucionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_devolucionesMouseClicked
        int seleccion = tb_devoluciones.rowAtPoint(evt.getPoint());
        txt_idprestamo.setText(String.valueOf(tb_devoluciones.getValueAt(seleccion, 0)));
        txt_usuario.setText(String.valueOf(tb_devoluciones.getValueAt(seleccion, 1)));
        txt_idmaterial.setText(String.valueOf(tb_devoluciones.getValueAt(seleccion, 2)));
        txt_fecha_prestamo.setText(String.valueOf(tb_devoluciones.getValueAt(seleccion, 3)));
        txt_fecha_entrega.setText(String.valueOf(tb_devoluciones.getValueAt(seleccion, 4)));
    }//GEN-LAST:event_tb_devolucionesMouseClicked

    private void txt_buscar_documentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscar_documentoKeyTyped
        switch (cbm_buscar.getSelectedIndex()) {
            case 1:

                txt_buscar_documento.addKeyListener(new KeyAdapter() {
                    @Override
                    public void keyReleased(KeyEvent e) {
                        trs.setRowFilter(RowFilter.regexFilter("(?i)" + txt_buscar_documento.getText(), 1));
                    }

                });
                trs = new TableRowSorter<>(tb_devoluciones.getModel());
                tb_devoluciones.setRowSorter(trs);
                break;
            case 2:

                break;
            default:
                JOptionPane.showMessageDialog(null, "Por favor seleccione un tipo de busqueda");
                break;
        }
    }//GEN-LAST:event_txt_buscar_documentoKeyTyped

    private void btmbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmbuscarActionPerformed
        if (fecha_prestamo.getDate() == null) {
            JOptionPane.showMessageDialog(null, "INGRESE FECHA DE PRESTAMO");
        } else {
            Object file[] = new Object[modelo_devoluciones.getColumnCount()];
            modelo_devoluciones.setRowCount(0);
            for (Abstracciones.Abs_prestamo d : Metodos.Metodos.lista_prestamo) {

                int valor = fecha_prestamo.getDate().compareTo(d.getFecha_prestamo());
                if (d.getId_usuario() == Long.parseLong(txt_buscar_documento.getText()) && valor == 0) {
                    String fecha = new SimpleDateFormat("dd/MM/yyyy").format(d.getFecha_prestamo());
                    String fecha1 = new SimpleDateFormat("dd/MM/yyyy").format(d.getFecha_entrega());
                    file[0] = d.getId_prestamo();
                    file[1] = d.getId_usuario();
                    file[2] = d.getId_material();
                    file[3] = fecha;
                    file[4] = fecha1;
                    file[5] = d.getEstado();
                    modelo_devoluciones.addRow(file);
                }
            }
        }

    }//GEN-LAST:event_btmbuscarActionPerformed

    private void cbm_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbm_buscarActionPerformed
        if (cbm_buscar.getSelectedIndex() == 1) {
            cargartabla_devolciones();
        }
    }//GEN-LAST:event_cbm_buscarActionPerformed

    private void btm_validarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_validarActionPerformed
        if (fecha_Actual.getDate() != null) {
            Date fechaInicial = null;
            Date fechaFinal = fecha_Actual.getDate();
            String deuda;
            //CONVIERTO DE STRING A DATE
            try {
                fechaInicial = new SimpleDateFormat("dd/MM/yyyy").parse(txt_fecha_entrega.getText());

            } catch (ParseException ex) {
                Logger.getLogger(R_devoluciones.class.getName()).log(Level.SEVERE, null, ex);
            }
            //CALCULO LA DIFERENCIA DE LAS FECHAS DE ENTREGA
            int dias_diferencia = Metodos.Metodos.diferencia_dias_fecha(fechaFinal, fechaInicial);
            //SI LA DIFERENCIA ES = O MAYOR A UNO, COBRO LA MULTA
            if (dias_diferencia >= 1) {
                int multa = dias_diferencia * 1000;
                String botones[] = {"Pagar", "No pagar"};
                int eleccion = JOptionPane.showOptionDialog(this, "USTED DEBE CANCELAR UNA MULTA DE $" + multa + " Pesos"
                        + "\n DIAS DE RETARTODO DE ENTREGA: " + dias_diferencia,
                        "Advertencia", 0, 0, null, botones, this);
                //SI EL USUARIO DECIDE PAGAR CONFIRMO DEVOLUCION
                if (eleccion == JOptionPane.YES_OPTION) {

                    long id_prestamo = Long.parseLong(txt_idprestamo.getText());
                    //SI EL PRESTAMO YA FUE DEVUELTO, ME VOTA UN ERRO. DE LO CONTRARIO
                    //CONTINUA CON LA DEVOLUCION
                    if (comprobar_entrega(id_prestamo) == false) {
                        long id_devoluciones = Metodos.Metodos.lista_devoluciones.size() + 1;
                        long id_usuario = Long.parseLong(txt_usuario.getText());
                        long id_material = Long.parseLong(txt_idmaterial.getText());
                        Date fecha_devolucion = fecha_Actual.getDate();
                        //AGREGO EL REGISTRO DE LA DEVOLUCION
                        Metodos.Metodos.InsertarDevolucion(new Abs_devoluciones(id_devoluciones, id_usuario, id_material, fecha_devolucion));
                        Metodos.Metodos.agregar_devolucion_lista(new Abs_devoluciones(id_devoluciones, id_usuario, id_material, fecha_devolucion));

                        //ACTUALIZO LA CANTIDAD DISPONIBLE EN LA LISTA DE MATERIALES
                        aumentar_cantidad_material(id_material);
                        //GUARDO LAS MODIFICACIONES EN LOS ARCHIVOS
                        Metodos.Metodos.guarda_modificacion_materiales();
                        Metodos.Metodos.guarda_modificacion_prestamos();
                        cargartabla_devolciones();
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "POR FAVOR CANCELAR LOS ANTES POSIBLE \n ENTRE MAS DIAS SU DEUDA CRECE");
                }

            } else if (dias_diferencia < 1) {
                //SI LOS DIAS DE DIFERENCIA SON MENOR A UNO NO SE COBRA MULTA
                long id_prestamo = Long.parseLong(txt_idprestamo.getText());
                    //SI EL PRESTAMO YA FUE DEVUELTO, ME VOTA UN ERRO. DE LO CONTRARIO
                    //CONTINUA CON LA DEVOLUCION
                    if (comprobar_entrega(id_prestamo) == false) {
                        long id_devoluciones = Metodos.Metodos.lista_devoluciones.size() + 1;
                        long id_usuario = Long.parseLong(txt_usuario.getText());
                        long id_material = Long.parseLong(txt_idmaterial.getText());
                        Date fecha_devolucion = fecha_Actual.getDate();
                        //AGREGO EL REGISTRO DE LA DEVOLUCION
                        Metodos.Metodos.InsertarDevolucion(new Abs_devoluciones(id_devoluciones, id_usuario, id_material, fecha_devolucion));
                        Metodos.Metodos.agregar_devolucion_lista(new Abs_devoluciones(id_devoluciones, id_usuario, id_material, fecha_devolucion));

                        //ACTUALIZO LA CANTIDAD DISPONIBLE EN LA LISTA DE MATERIALES
                        aumentar_cantidad_material(id_material);
                        //GUARDO LAS MODIFICACIONES EN LOS ARCHIVOS
                        Metodos.Metodos.guarda_modificacion_materiales();
                        Metodos.Metodos.guarda_modificacion_prestamos();
                        cargartabla_devolciones();
                         JOptionPane.showMessageDialog(null, "GRACIAS POR ENTREGAR EL LIBRO A TIEMPO");
                    }
                   

            }

        } else {
            JOptionPane.showMessageDialog(null, "INGRESE FECHA DE ACTUAL");
        }
    }//GEN-LAST:event_btm_validarActionPerformed
    private void aumentar_cantidad_material(long id_m) {
        long id_prestamo = Long.parseLong(txt_idprestamo.getText());
        Iterator<Abs_material> buscar = Metodos.Metodos.lista_materiales.iterator();
        for (Abs_material n : Metodos.Metodos.lista_materiales) {
            n = buscar.next();
            if (id_m == n.getId_material()) {
                n.setCantidad(n.getCantidad() + 1);
                break;
            }
        }
        for (Abstracciones.Abs_prestamo d : Metodos.Metodos.lista_prestamo) {
            if (id_prestamo == d.getId_prestamo()) {
                d.setEstado("ENTREGADO");
            }
        }
    }

    private boolean comprobar_entrega(long id_prestamo) {
        boolean ya_entregado = false;
        for (Abstracciones.Abs_prestamo d : Metodos.Metodos.lista_prestamo) {
            if (id_prestamo == d.getId_prestamo()) {
                if (d.getEstado().equals("ENTREGADO")) {
                    ya_entregado = true;
                    JOptionPane.showMessageDialog(null, "EL PRESTAMO: " + d.getId_prestamo() + "\n Ya fue entregado");
                    break;
                }
            }
        }
        return ya_entregado;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(R_devoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(R_devoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(R_devoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(R_devoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new R_devoluciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btm_validar;
    private javax.swing.JButton btmbuscar;
    private javax.swing.JComboBox<String> cbm_buscar;
    private com.toedter.calendar.JDateChooser fecha_Actual;
    private com.toedter.calendar.JDateChooser fecha_prestamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_devoluciones;
    private javax.swing.JTextField txt_buscar_documento;
    private javax.swing.JTextField txt_fecha_entrega;
    private javax.swing.JTextField txt_fecha_prestamo;
    private javax.swing.JTextField txt_idmaterial;
    private javax.swing.JTextField txt_idprestamo;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
