/*
 * Este codigo fue creado por @DuvanBotello
 *  <"Sin lógica no hay paraíso">
 */
package GUI;

import Abstracciones.Abs_Empleado;
import java.awt.event.KeyEvent;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author DuvanBotello
 * <http://yoaprendo-informatica.blogspot.com.co/ - duvanbotello1008@gmail.com>
 */
public class R_empleados extends javax.swing.JFrame {

    /**
     * Creates new form R_empleados
     */
    public R_empleados() {
        initComponents();
        this.setLocationRelativeTo(null);
        Metodos.Metodos.icono_proyecto(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtcontraseña = new javax.swing.JTextField();
        txtnombres = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbmrol = new javax.swing.JComboBox<>();
        txttelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btmregistrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtdocumento1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REGISTRO DE EMPLEADOS - BIBLIOTECA UNIPAMPLONA");
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 100, 30));

        txtcontraseña.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtcontraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtcontraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcontraseñaKeyTyped(evt);
            }
        });
        getContentPane().add(txtcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 180, 30));

        txtnombres.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtnombres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtnombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombresKeyTyped(evt);
            }
        });
        getContentPane().add(txtnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 180, 30));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("Nombres:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 90, 30));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("Rol:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 40, 30));

        cbmrol.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cbmrol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Administrador", "Empleado" }));
        cbmrol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cbmrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmrolActionPerformed(evt);
            }
        });
        getContentPane().add(cbmrol, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 180, 30));

        txttelefono.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txttelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 180, 30));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Telefono:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 80, 30));

        btmregistrar.setBackground(new java.awt.Color(0, 0, 0));
        btmregistrar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btmregistrar.setForeground(new java.awt.Color(255, 255, 255));
        btmregistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_registrar.png"))); // NOI18N
        btmregistrar.setText("Registrar");
        btmregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmregistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btmregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 160, 50));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Documento:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, 30));

        txtdocumento1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtdocumento1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtdocumento1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdocumento1KeyTyped(evt);
            }
        });
        getContentPane().add(txtdocumento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 180, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registro_empleados.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcontraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontraseñaKeyTyped
        char teclaseleccionada = evt.getKeyChar();
        if (teclaseleccionada == KeyEvent.VK_ENTER || teclaseleccionada == KeyEvent.VK_I) {
            btmregistrar.doClick();
        }
    }//GEN-LAST:event_txtcontraseñaKeyTyped

    private void txtnombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombresKeyTyped
        char teclaseleccionada = evt.getKeyChar();
        if (teclaseleccionada == KeyEvent.VK_ENTER || teclaseleccionada == KeyEvent.VK_I) {
            btmregistrar.doClick();
        }

        if (Character.isDigit(teclaseleccionada)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "SOLO SE PUEDEN INGRESAR LETRAS EN EL CAMPO");
        }
    }//GEN-LAST:event_txtnombresKeyTyped

    private void cbmrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmrolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmrolActionPerformed

    private void txttelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyTyped
        char teclaseleccionada = evt.getKeyChar();
        if (teclaseleccionada == KeyEvent.VK_ENTER || teclaseleccionada == KeyEvent.VK_I) {
            btmregistrar.doClick();
        }
        if (Character.isLetter(teclaseleccionada)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "SOLO SE PUEDEN INGRESAR NUMEROS EN EL CAMPO");
        }
    }//GEN-LAST:event_txttelefonoKeyTyped

    private void btmregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmregistrarActionPerformed
        //COMPRUEBO QUE TODOS LOS CAMPOS ESTEN LLENOS
        if (!txtdocumento1.getText().isEmpty()) {
            if (!txtcontraseña.getText().isEmpty()) {
                if (!txtnombres.getText().isEmpty()) {
                    if (cbmrol.getSelectedIndex() != 0) {
                        if (!txttelefono.getText().isEmpty()) {

                            try {
                                //COVIERTO LO QUE ESTA DENTRO DE LOS TEXTOS EN SUS RESPECTIVOS VALORES
                                long documento = Long.parseLong(txtdocumento1.getText().trim());
                                String nombre = txtnombres.getText();
                                String contraseña = txtcontraseña.getText();
                                int rol = 0;
                                if (cbmrol.getSelectedIndex() == 1) {
                                    rol = 1; //si es 1 es Administrador
                                }
                                if (cbmrol.getSelectedIndex() == 2) {
                                    rol = 2; //si es 2 Empleado
                                }
                               
                                int telefono = Integer.parseInt(txttelefono.getText().trim());
                                //COMPRUEBO SI YA EXISTE EL USUARIO
                                boolean existe = false;
                                Abs_Empleado b;
                                Iterator<Abs_Empleado> buscar = Abs_Empleado.lista_rempleados.iterator();
                                for (int i = 0; i < Abs_Empleado.lista_rempleados.size(); i++) {
                                    b = buscar.next();
                                    if (b.getId_usuario() == documento) {
                                        existe = true;
                                        JOptionPane.showMessageDialog(null, "Empleado: " + b.getId_usuario() + " Ya existe" + "\n" + "Nombre: " + b.getNombre());
                                    }
                                }
                                if (existe == false) {
                                    //SI NO EXISTE LOS CREO
                                    Abs_Empleado.Insertar_Empleado(new Abs_Empleado(contraseña, documento, nombre, rol, telefono));
                                    Abs_Empleado.add_listaempleados(new Abs_Empleado(contraseña, documento, nombre, rol, telefono));
                                    txtcontraseña.setText("");
                                    txtnombres.setText("");
                                    txttelefono.setText("");
                                    cbmrol.setSelectedIndex(0);
                                    txtdocumento1.setText("");
                                }
                            } catch (Exception e) {
                                JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR, REVISE LOS CAMPOS");
                            }

                        } else {
                            JOptionPane.showMessageDialog(null, "POR FAVOR INGRESE TELEFONO");
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "POR FAVOR SELECCIONE ROL");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "POR FAVOR INGRESAR NOMBRE");
                }

            } else {
                JOptionPane.showMessageDialog(null, "POR FAVOR INGRESAR CONTRASEÑA");
            }
        } else {
            JOptionPane.showMessageDialog(null, "POR FAVOR INGRESAR DOCUMENTO");
        }


    }//GEN-LAST:event_btmregistrarActionPerformed

    private void txtdocumento1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdocumento1KeyTyped
      char teclaseleccionada = evt.getKeyChar();
        if (teclaseleccionada == KeyEvent.VK_ENTER || teclaseleccionada == KeyEvent.VK_I) {
            btmregistrar.doClick();
        }
        if (Character.isLetter(teclaseleccionada)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "SOLO SE PUEDEN INGRESAR NUMEROS EN EL CAMPO");
        }
    }//GEN-LAST:event_txtdocumento1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(R_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(R_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(R_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(R_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new R_empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmregistrar;
    private javax.swing.JComboBox<String> cbmrol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtcontraseña;
    private javax.swing.JTextField txtdocumento1;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
