/*
 * Este codigo fue creado por @DuvanBotello
 *  <"Sin lógica no hay paraíso">
 */
package GUI;

import Abstracciones.Abs_material;
import Abstracciones.Abs_prestamo;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author DuvanBotello
 * <http://yoaprendo-informatica.blogspot.com.co/ - duvanbotello1008@gmail.com>
 */
public class R_prestamos extends javax.swing.JFrame {

    DefaultTableModel modelomaeriales = new DefaultTableModel();
    DefaultTableModel modelousuarios = new DefaultTableModel();
    private TableRowSorter<TableModel> trs;
    int tipo_busqueda = 0;

    /**
     * Creates new form R_prestamos
     */
    public R_prestamos() {
        initComponents();
        this.setLocationRelativeTo(null);
        modelomaeriales.addColumn("ID");
        modelomaeriales.addColumn("NOMBRE");
        modelomaeriales.addColumn("TIPO");
        modelomaeriales.addColumn("EDITORIAL");
        modelomaeriales.addColumn("CANTIDAD");
        tbmateriales.setModel(modelomaeriales);

        modelousuarios.addColumn("ID");
        modelousuarios.addColumn("NOMBRE");
        modelousuarios.addColumn("TIPO");
        modelousuarios.addColumn("TELEFONO");
        tbusuarios.setModel(modelousuarios);

        cargar_tabla_materiales();
        cargar_tabla_usuarios();
        Metodos.Metodos.icono_proyecto(this);
    }

    private void cargar_tabla_materiales() {
        modelomaeriales.setRowCount(0);
        Iterator<Abstracciones.Abs_material> buscar1 = Metodos.Metodos.lista_materiales.iterator();
        Object file[] = new Object[tbmateriales.getColumnCount()];
        for (Abs_material f : Metodos.Metodos.lista_materiales) {
            String tipo1 = "";
            f = buscar1.next();
            file[0] = f.getId_material();
            file[1] = f.getNombre();
            if (f.getTipo() == 1) {
                tipo1 = "Libro";
            }
            if (f.getTipo() == 2) {
                tipo1 = "Revista";
            }
            if (f.getTipo() == 3) {
                tipo1 = "Tesis";
            }
            file[2] = tipo1;
            file[3] = f.getEditorial();
            file[4] = f.getCantidad();
            modelomaeriales.addRow(file);
        }
    }

    private void cargar_tabla_usuarios() {
        modelousuarios.setRowCount(0);
        Iterator<Abstracciones.Abs_usuario> buscar2 = Metodos.Metodos.Lista_usuarios.iterator();
        Object file[] = new Object[tbusuarios.getColumnCount()];
        for (Abstracciones.Abs_usuario d : Metodos.Metodos.Lista_usuarios) {

            d = buscar2.next();
            String tipo1 = "";
            if (d.getRol() == 1) {
                tipo1 = "Estudiante";
            }
            if (d.getRol() == 2) {
                tipo1 = "Profesor";
            }
            if (d.getRol() == 3) {
                tipo1 = "externo";
            }
            file[0] = d.getId_usuario();
            file[1] = d.getNombre();
            file[2] = tipo1;
            file[3] = d.getTelefono();
            modelousuarios.addRow(file);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbusuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cbm_buscarusuario = new javax.swing.JComboBox<>();
        txt_buscarusuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbmateriales = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cbmbuscarmateriales = new javax.swing.JComboBox<>();
        txtbuscar_material = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        Panel_Datos = new javax.swing.JPanel();
        du_telefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Panel_Datos1 = new javax.swing.JPanel();
        txt_id1 = new javax.swing.JTextField();
        txtnombre_m1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_editorial1 = new javax.swing.JTextField();
        txt_cantidad1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbm_tipo1 = new javax.swing.JComboBox<>();
        du_documento = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        du_nombre = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        Panel_Datos2 = new javax.swing.JPanel();
        dm_id = new javax.swing.JTextField();
        dm_nombre = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        dm_tipo = new javax.swing.JTextField();
        dm_cantidad = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        Panel_Datos3 = new javax.swing.JPanel();
        txt_id3 = new javax.swing.JTextField();
        txtnombre_m3 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_editorial3 = new javax.swing.JTextField();
        txt_cantidad3 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        cbm_tipo3 = new javax.swing.JComboBox<>();
        dm_editorial = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        id_usuario = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        p_id_libro = new javax.swing.JTextField();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabel27 = new javax.swing.JLabel();
        btm_nuevo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel34 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PRESTAMOS - BIBLIOETCA UNIPAMPLONA");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Buscar Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbusuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbusuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbusuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbusuarios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 469, 190));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("BUSCAR POR:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        cbm_buscarusuario.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cbm_buscarusuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "DOCUMENTO", "NOMBRE" }));
        cbm_buscarusuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(cbm_buscarusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 138, -1));

        txt_buscarusuario.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txt_buscarusuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_buscarusuario.setText("buscar");
        txt_buscarusuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_buscarusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_buscarusuarioMouseClicked(evt);
            }
        });
        txt_buscarusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_buscarusuarioKeyTyped(evt);
            }
        });
        jPanel1.add(txt_buscarusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 230, 20));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("BUSCAR USUARIO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 260));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 498, 260));

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Buscar Material", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbmateriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbmateriales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbmaterialesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbmateriales);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 469, 190));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("BUSCAR POR:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        cbmbuscarmateriales.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        cbmbuscarmateriales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "ID", "NOMBRE", "TIPO", "EDITORIAL", "CANTIDAD" }));
        cbmbuscarmateriales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(cbmbuscarmateriales, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 138, -1));

        txtbuscar_material.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtbuscar_material.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtbuscar_material.setText("buscar");
        txtbuscar_material.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtbuscar_material.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtbuscar_materialMouseClicked(evt);
            }
        });
        txtbuscar_material.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscar_materialActionPerformed(evt);
            }
        });
        txtbuscar_material.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscar_materialKeyTyped(evt);
            }
        });
        jPanel2.add(txtbuscar_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 234, 20));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BUSCAR MATERIAL");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 260));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 490, 260));

        Panel_Datos.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Datos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos de Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 14))); // NOI18N
        Panel_Datos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        du_telefono.setEditable(false);
        du_telefono.setBackground(new java.awt.Color(0, 204, 102));
        du_telefono.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        du_telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        du_telefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        du_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                du_telefonoActionPerformed(evt);
            }
        });
        Panel_Datos.add(du_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 190, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Documento:");
        Panel_Datos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, 20));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Telefono:");
        Panel_Datos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, 20));

        Panel_Datos1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos de material", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 11))); // NOI18N
        Panel_Datos1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_id1.setEditable(false);
        txt_id1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txt_id1.setForeground(new java.awt.Color(255, 0, 0));
        txt_id1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_id1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id1ActionPerformed(evt);
            }
        });
        Panel_Datos1.add(txt_id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 140, -1));

        txtnombre_m1.setEditable(false);
        txtnombre_m1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtnombre_m1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtnombre_m1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombre_m1KeyTyped(evt);
            }
        });
        Panel_Datos1.add(txtnombre_m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 140, -1));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Nombre:");
        Panel_Datos1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("ID:");
        Panel_Datos1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 20));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Tipo:");
        Panel_Datos1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, 20));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Editorial:");
        Panel_Datos1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, 20));

        txt_editorial1.setEditable(false);
        txt_editorial1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txt_editorial1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_editorial1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_editorial1KeyTyped(evt);
            }
        });
        Panel_Datos1.add(txt_editorial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 140, -1));

        txt_cantidad1.setEditable(false);
        txt_cantidad1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txt_cantidad1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_cantidad1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cantidad1KeyTyped(evt);
            }
        });
        Panel_Datos1.add(txt_cantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 50, -1));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Cant:");
        Panel_Datos1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, 20));

        cbm_tipo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Libro", "Revista", "Tesis" }));
        cbm_tipo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panel_Datos1.add(cbm_tipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 140, -1));

        Panel_Datos.add(Panel_Datos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 490, 130));

        du_documento.setEditable(false);
        du_documento.setBackground(new java.awt.Color(0, 204, 102));
        du_documento.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        du_documento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        du_documento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        du_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                du_documentoActionPerformed(evt);
            }
        });
        Panel_Datos.add(du_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 190, -1));

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("Nombre:");
        Panel_Datos.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, 20));

        du_nombre.setEditable(false);
        du_nombre.setBackground(new java.awt.Color(0, 204, 102));
        du_nombre.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        du_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        du_nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        du_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                du_nombreActionPerformed(evt);
            }
        });
        Panel_Datos.add(du_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 190, -1));

        jLabel33.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("DATOS DE USUARIO");
        Panel_Datos.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panel_Datos.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 130));

        getContentPane().add(Panel_Datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 500, 130));

        Panel_Datos2.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Datos2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos de material", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 14))); // NOI18N
        Panel_Datos2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dm_id.setEditable(false);
        dm_id.setBackground(new java.awt.Color(0, 204, 102));
        dm_id.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        dm_id.setForeground(new java.awt.Color(255, 0, 0));
        dm_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dm_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dm_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dm_idActionPerformed(evt);
            }
        });
        Panel_Datos2.add(dm_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 140, -1));

        dm_nombre.setEditable(false);
        dm_nombre.setBackground(new java.awt.Color(0, 204, 102));
        dm_nombre.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        dm_nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dm_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dm_nombreKeyTyped(evt);
            }
        });
        Panel_Datos2.add(dm_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 140, -1));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Nombre:");
        Panel_Datos2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("ID:");
        Panel_Datos2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 20));

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Tipo:");
        Panel_Datos2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, 20));

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Editorial:");
        Panel_Datos2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, 20));

        dm_tipo.setEditable(false);
        dm_tipo.setBackground(new java.awt.Color(0, 204, 102));
        dm_tipo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        dm_tipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dm_tipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dm_tipoKeyTyped(evt);
            }
        });
        Panel_Datos2.add(dm_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 140, -1));

        dm_cantidad.setEditable(false);
        dm_cantidad.setBackground(new java.awt.Color(0, 204, 102));
        dm_cantidad.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        dm_cantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dm_cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dm_cantidadKeyTyped(evt);
            }
        });
        Panel_Datos2.add(dm_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 50, -1));

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Cant:");
        Panel_Datos2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, 20));

        Panel_Datos3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos de material", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 11))); // NOI18N
        Panel_Datos3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_id3.setEditable(false);
        txt_id3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txt_id3.setForeground(new java.awt.Color(255, 0, 0));
        txt_id3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_id3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_id3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id3ActionPerformed(evt);
            }
        });
        Panel_Datos3.add(txt_id3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 140, -1));

        txtnombre_m3.setEditable(false);
        txtnombre_m3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtnombre_m3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtnombre_m3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombre_m3KeyTyped(evt);
            }
        });
        Panel_Datos3.add(txtnombre_m3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 140, -1));

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Nombre:");
        Panel_Datos3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("ID:");
        Panel_Datos3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 20));

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Tipo:");
        Panel_Datos3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, 20));

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Editorial:");
        Panel_Datos3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, 20));

        txt_editorial3.setEditable(false);
        txt_editorial3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txt_editorial3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_editorial3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_editorial3KeyTyped(evt);
            }
        });
        Panel_Datos3.add(txt_editorial3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 140, -1));

        txt_cantidad3.setEditable(false);
        txt_cantidad3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txt_cantidad3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_cantidad3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cantidad3KeyTyped(evt);
            }
        });
        Panel_Datos3.add(txt_cantidad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 50, -1));

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Cant:");
        Panel_Datos3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, 20));

        cbm_tipo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Libro", "Revista", "Tesis" }));
        cbm_tipo3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panel_Datos3.add(cbm_tipo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 140, -1));

        Panel_Datos2.add(Panel_Datos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 490, 130));

        dm_editorial.setEditable(false);
        dm_editorial.setBackground(new java.awt.Color(0, 204, 102));
        dm_editorial.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        dm_editorial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dm_editorial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dm_editorialKeyTyped(evt);
            }
        });
        Panel_Datos2.add(dm_editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 140, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DATOS DE MATERIAL");
        Panel_Datos2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panel_Datos2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 130));

        getContentPane().add(Panel_Datos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 490, 130));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Validar Prestamo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel25.setText("ID DE LIBRO:");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 20));

        id_usuario.setEditable(false);
        id_usuario.setBackground(new java.awt.Color(255, 153, 153));
        id_usuario.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        id_usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id_usuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        id_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_usuarioActionPerformed(evt);
            }
        });
        jPanel3.add(id_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 140, -1));

        jLabel26.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel26.setText("ID DE USUARIO:");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, 20));

        p_id_libro.setEditable(false);
        p_id_libro.setBackground(new java.awt.Color(255, 153, 153));
        p_id_libro.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        p_id_libro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p_id_libro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p_id_libro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_id_libroActionPerformed(evt);
            }
        });
        jPanel3.add(p_id_libro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, -1));

        fecha.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel3.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 133, -1));

        jLabel27.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel27.setText("FECHA DE PRESTAMO:");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, 20));

        btm_nuevo.setBackground(new java.awt.Color(0, 0, 0));
        btm_nuevo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btm_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        btm_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ico_validar.png"))); // NOI18N
        btm_nuevo.setText("Validar Prestamo");
        btm_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_nuevoActionPerformed(evt);
            }
        });
        jPanel3.add(btm_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 190, 50));

        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"LIBRO", "3 DIAS"},
                {"REVISTA", "4 DIAS"},
                {"TESIS", "5 DIAS"}
            },
            new String [] {
                "MATERIAL", "TIEMPO DE PRESTAMO"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 250, 80));

        jLabel34.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("DATOS DE PRESTAMO");
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 160));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 520, 160));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_prestamos.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void du_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_du_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_du_telefonoActionPerformed

    private void txt_id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id1ActionPerformed

    private void txtnombre_m1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombre_m1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombre_m1KeyTyped

    private void txt_editorial1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_editorial1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_editorial1KeyTyped

    private void txt_cantidad1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cantidad1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidad1KeyTyped

    private void txt_cantidad3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cantidad3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidad3KeyTyped

    private void txt_editorial3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_editorial3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_editorial3KeyTyped

    private void txtnombre_m3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombre_m3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombre_m3KeyTyped

    private void txt_id3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id3ActionPerformed

    private void dm_cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dm_cantidadKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_dm_cantidadKeyTyped

    private void dm_tipoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dm_tipoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_dm_tipoKeyTyped

    private void dm_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dm_nombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_dm_nombreKeyTyped

    private void dm_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dm_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dm_idActionPerformed

    private void du_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_du_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_du_documentoActionPerformed

    private void du_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_du_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_du_nombreActionPerformed

    private void id_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_usuarioActionPerformed

    private void p_id_libroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_id_libroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_id_libroActionPerformed

    private void btm_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_nuevoActionPerformed
        //QUE NO ESTE LA FECHA VACIA
        if (fecha.getDate() != null) {
            if (!id_usuario.getText().isEmpty()) {
                if (!p_id_libro.getText().isEmpty()) {
                    long id_prestamo = Metodos.Metodos.lista_prestamo.size() + 1;
                    String fecha1 = new SimpleDateFormat("dd/MM/yyyy").format(fecha.getDate());
                    String botones[] = {"Prestar", "Cancelar"};
                    Date fecha_Entrega = dias_de_prestamo_segun_material();
                    String fecha2 = new SimpleDateFormat("dd/MM/yyyy").format(fecha_Entrega);
                    int eleccion = JOptionPane.showOptionDialog(this, "¿Seguro que deseas prestar?" + "\n ID_PRESTAMO: " + id_prestamo + "\n ID USUARIO: " + du_documento.getText()
                            + "\n ID DE MATERIAL: " + dm_id.getText() + "\nFECHA DE PRESTAMO: " + fecha1 + "\n FECHA DE ENTREGA: " + fecha2,
                            "Advertencia", 0, 0, null, botones, this);
                    if (eleccion == JOptionPane.YES_OPTION) {
                        //EL LIBRO TIENE QUE TENER UNIDADES DISPONIBLES
                        if (Integer.parseInt(dm_cantidad.getText()) >= 1) {
                            long id_usu = Long.parseLong(du_documento.getText());
                            long id_material = Long.parseLong(dm_id.getText());
                            //AGREGO EL PRESTAMO AL CONTENEDOR
                            Metodos.Metodos.agregar_prestamo_lista(new Abs_prestamo(id_prestamo, id_usu, id_material, fecha.getDate(), fecha_Entrega, "POR ENTREGAR"));
                            Metodos.Metodos.InsertarPrestamo(new Abs_prestamo(id_prestamo, id_usu, id_material, fecha.getDate(), fecha_Entrega, "POR ENTREGAR"));
                            long id_m = Long.parseLong(dm_id.getText());
                            int cant = Integer.parseInt(dm_cantidad.getText());
                            //MODIFICO EL VALOR DE CANTIDAD DEL LIBRO
                            Iterator<Abs_material> buscar = Metodos.Metodos.lista_materiales.iterator();
                            for (Abs_material n : Metodos.Metodos.lista_materiales) {
                                n = buscar.next();
                                if (id_m == n.getId_material()) {
                                    n.setCantidad(cant - 1);
                                    break;
                                }
                            }
                            Metodos.Metodos.guarda_modificacion_materiales();
                 
                            cargar_tabla_materiales();
                            limpiar_campos();

                        } else {
                            JOptionPane.showMessageDialog(null, "No hay unidades disponibles");
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "SELECCIONE UN MATERIAL");
                }
            } else {
                JOptionPane.showMessageDialog(null, "SELECCIONE UN USUARIO");
            }
        } else {
            JOptionPane.showMessageDialog(null, "INGRESE UNA FECHA DE PRESTAMO");
        }

    }//GEN-LAST:event_btm_nuevoActionPerformed
    private Date dias_de_prestamo_segun_material() {
        Date fechaentrega = null;
//        e.setText(fecha2);
        if (dm_tipo.getText().equals("Libro")) {
            fechaentrega = Metodos.Metodos.sumarDiasAFecha(fecha.getDate(), 3);
        }
        if (dm_tipo.getText().equals("Revista")) {
            fechaentrega = Metodos.Metodos.sumarDiasAFecha(fecha.getDate(), 4);
        }
        if (dm_tipo.getText().equals("Tesis")) {
            fechaentrega = Metodos.Metodos.sumarDiasAFecha(fecha.getDate(), 5);
        }
        return fechaentrega;
    }

    private void limpiar_campos() {
        dm_cantidad.setText("");
        dm_editorial.setText("");
        dm_id.setText("");
        dm_nombre.setText("");
        dm_tipo.setText("");
        du_documento.setText("");
        du_nombre.setText("");
        du_telefono.setText("");
        p_id_libro.setText("");
        id_usuario.setText("");
        fecha.setDate(null);

    }


    private void dm_editorialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dm_editorialKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_dm_editorialKeyTyped
    private void tipo_de_busqueda_ma() {
        if (cbmbuscarmateriales.getSelectedIndex() == 1) {
            tipo_busqueda = 0;
        }
        if (cbmbuscarmateriales.getSelectedIndex() == 2) {
            tipo_busqueda = 1;
        }
        if (cbmbuscarmateriales.getSelectedIndex() == 3) {
            tipo_busqueda = 2;
        }
        if (cbmbuscarmateriales.getSelectedIndex() == 4) {
            tipo_busqueda = 3;
        }
        if (cbmbuscarmateriales.getSelectedIndex() == 5) {
            tipo_busqueda = 4;
        }
    }

    private void tipo_de_busqueda_usu() {
        if (cbm_buscarusuario.getSelectedIndex() == 1) {
            tipo_busqueda = 0;
        }
        if (cbm_buscarusuario.getSelectedIndex() == 2) {
            tipo_busqueda = 1;
        }
    }
    private void txtbuscar_materialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscar_materialKeyTyped

        if (cbmbuscarmateriales.getSelectedIndex() != 0) {

            tipo_de_busqueda_ma();
            txtbuscar_material.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) {
                    trs.setRowFilter(RowFilter.regexFilter("(?i)" + txtbuscar_material.getText(), tipo_busqueda));
                }

            });
            trs = new TableRowSorter<>(tbmateriales.getModel());
            tbmateriales.setRowSorter(trs);

        } else {
            JOptionPane.showMessageDialog(null, "Por favor seleccione un tipo de busqueda");
        }

    }//GEN-LAST:event_txtbuscar_materialKeyTyped

    private void txtbuscar_materialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscar_materialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscar_materialActionPerformed

    private void txt_buscarusuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarusuarioKeyTyped
        if (cbm_buscarusuario.getSelectedIndex() != 0) {

            tipo_de_busqueda_usu();
            txt_buscarusuario.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) {
                    trs.setRowFilter(RowFilter.regexFilter("(?i)" + txt_buscarusuario.getText(), tipo_busqueda));
                }

            });
            trs = new TableRowSorter<>(tbusuarios.getModel());
            tbusuarios.setRowSorter(trs);

        } else {
            JOptionPane.showMessageDialog(null, "Por favor seleccione un tipo de busqueda");
            txt_buscarusuario.setText("");
        }
    }//GEN-LAST:event_txt_buscarusuarioKeyTyped

    private void tbmaterialesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbmaterialesMouseClicked

        int seleccion = tbmateriales.rowAtPoint(evt.getPoint());
        dm_id.setText(String.valueOf(tbmateriales.getValueAt(seleccion, 0)));
        dm_nombre.setText(String.valueOf(tbmateriales.getValueAt(seleccion, 1)));
        dm_tipo.setText(String.valueOf(tbmateriales.getValueAt(seleccion, 2)));
        dm_editorial.setText(String.valueOf(tbmateriales.getValueAt(seleccion, 3)));
        dm_cantidad.setText(String.valueOf(tbmateriales.getValueAt(seleccion, 4)));
        p_id_libro.setText(String.valueOf(tbmateriales.getValueAt(seleccion, 0)));
    }//GEN-LAST:event_tbmaterialesMouseClicked

    private void tbusuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbusuariosMouseClicked
        int seleccion = tbusuarios.rowAtPoint(evt.getPoint());
        du_documento.setText(String.valueOf(tbusuarios.getValueAt(seleccion, 0)));
        du_nombre.setText(String.valueOf(tbusuarios.getValueAt(seleccion, 1)));
        du_telefono.setText(String.valueOf(tbusuarios.getValueAt(seleccion, 3)));
        id_usuario.setText(String.valueOf(tbusuarios.getValueAt(seleccion, 0)));
    }//GEN-LAST:event_tbusuariosMouseClicked

    private void txtbuscar_materialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbuscar_materialMouseClicked
        if (txtbuscar_material.getText().equals("buscar")) {
            txtbuscar_material.setText("");
        }
    }//GEN-LAST:event_txtbuscar_materialMouseClicked

    private void txt_buscarusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_buscarusuarioMouseClicked
        if (txt_buscarusuario.getText().equals("buscar")) {
            txt_buscarusuario.setText("");
        }
    }//GEN-LAST:event_txt_buscarusuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(R_prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(R_prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(R_prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(R_prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new R_prestamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Datos;
    private javax.swing.JPanel Panel_Datos1;
    private javax.swing.JPanel Panel_Datos2;
    private javax.swing.JPanel Panel_Datos3;
    private javax.swing.JButton btm_nuevo;
    private javax.swing.JComboBox<String> cbm_buscarusuario;
    private javax.swing.JComboBox<String> cbm_tipo1;
    private javax.swing.JComboBox<String> cbm_tipo3;
    private javax.swing.JComboBox<String> cbmbuscarmateriales;
    private javax.swing.JTextField dm_cantidad;
    private javax.swing.JTextField dm_editorial;
    private javax.swing.JTextField dm_id;
    private javax.swing.JTextField dm_nombre;
    private javax.swing.JTextField dm_tipo;
    private javax.swing.JTextField du_documento;
    private javax.swing.JTextField du_nombre;
    private javax.swing.JTextField du_telefono;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JTextField id_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField p_id_libro;
    private javax.swing.JTable tbmateriales;
    private javax.swing.JTable tbusuarios;
    private javax.swing.JTextField txt_buscarusuario;
    private javax.swing.JTextField txt_cantidad1;
    private javax.swing.JTextField txt_cantidad3;
    private javax.swing.JTextField txt_editorial1;
    private javax.swing.JTextField txt_editorial3;
    private javax.swing.JTextField txt_id1;
    private javax.swing.JTextField txt_id3;
    private javax.swing.JTextField txtbuscar_material;
    private javax.swing.JTextField txtnombre_m1;
    private javax.swing.JTextField txtnombre_m3;
    // End of variables declaration//GEN-END:variables
}
